In [1]:
import numpy as np

Одномерные массивы (векторы)\
Создание массивов

In [3]:
a = np.array([2,3,4,4,5])
b = np.array([0,1,2.5,8])
c = np.array([1,2,3,'kf'])
print(a), print(type(a)), print(a.dtype)

[2 3 4 4 5]
<class 'numpy.ndarray'>
int32


(None, None, None)

In [4]:
print(b), print(type(b)), print(b.dtype)

[0.  1.  2.5 8. ]
<class 'numpy.ndarray'>
float64


(None, None, None)

In [5]:
print(c), print(type(c)), print(c.dtype)

['1' '2' '3' 'kf']
<class 'numpy.ndarray'>
<U11


(None, None, None)

In [6]:
b.astype(int)

array([0, 1, 2, 8])

In [10]:
zer, oness = np.zeros(4), np.ones(5, dtype='int')
zer, oness

(array([0., 0., 0., 0.]), array([1, 1, 1, 1, 1]))

In [11]:
np.zeros_like(oness)

array([0, 0, 0, 0, 0])

In [12]:
np.linspace(0, 100, 20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

Размер

In [14]:
a.ndim # размерность массива

1

In [16]:
a.shape # размер по координатам

(5,)

In [18]:
a.size # количество всех элементов

5

Индексация

In [21]:
d = a.copy()
d

array([2, 3, 4, 4, 5])

Нахождение уникальных элементов

In [22]:
np.unique(d, return_counts=True)

(array([2, 3, 4, 5]), array([1, 1, 2, 1], dtype=int64))

Математические операции

In [31]:
p = np.array([2,3,4,2,1,0,3])
q = np.array([2,3,4,31,2,4,1])

In [32]:
print(p*q)
print(p*2)
print(p**2)
print(p/q)

[ 4  9 16 62  2  0  3]
[4 6 8 4 2 0 6]
[ 4  9 16  4  1  0  9]
[1.         1.         1.         0.06451613 0.5        0.
 3.        ]


In [33]:
print(np.log(q))
print(np.sin(q))
print(np.exp(q))

[0.69314718 1.09861229 1.38629436 3.4339872  0.69314718 1.38629436
 0.        ]
[ 0.90929743  0.14112001 -0.7568025  -0.40403765  0.90929743 -0.7568025
  0.84147098]
[7.38905610e+00 2.00855369e+01 5.45981500e+01 2.90488497e+13
 7.38905610e+00 5.45981500e+01 2.71828183e+00]


In [34]:
p.sum(), p.prod(), p.max(), p.mean(), p.std()

(15, 0, 4, 2.142857142857143, 1.2453996981544782)

In [35]:
print(p<q)
print(p==q)
print(p>2)

[False False False  True  True  True False]
[ True  True  True False False False False]
[False  True  True False False False  True]


Соединение массивов

In [36]:
np.sort(p)

array([0, 1, 2, 2, 3, 3, 4])

In [37]:
np.append(p, q)

array([ 2,  3,  4,  2,  1,  0,  3,  2,  3,  4, 31,  2,  4,  1])

In [38]:
np.append(p, [1,1,1])

array([2, 3, 4, 2, 1, 0, 3, 1, 1, 1])

In [40]:
np.delete(p, [3])

array([2, 3, 4, 1, 0, 3])

In [41]:
p

array([2, 3, 4, 2, 1, 0, 3])

In [43]:
np.insert(p, 2, [100,100])

array([  2,   3, 100, 100,   4,   2,   1,   0,   3])

In [44]:
p.dot(q)

96

Двумерный массив

In [46]:
A = np.array([
    [2,3,4],
    [1,6,8],
    [6,5,7]
])

In [48]:
B = np.array([
    [2,3],
    [8,0],
    [2.5,3]
])

In [51]:
B.dtype

dtype('float64')

In [52]:
np.eye(2,1)

array([[1.],
       [0.]])

In [54]:
A.ndim, A.shape, A.size

(2, (3, 3), 9)

In [55]:
A.ravel()

array([2, 3, 4, 1, 6, 8, 6, 5, 7])

In [57]:
A.reshape(9) # указать кол-во элементов

array([2, 3, 4, 1, 6, 8, 6, 5, 7])

In [62]:
C = np.linspace(1,20,6)

In [64]:
C.shape = 2, 3
C

array([[ 1. ,  4.8,  8.6],
       [12.4, 16.2, 20. ]])

In [65]:
C.reshape(2,3)

array([[ 1. ,  4.8,  8.6],
       [12.4, 16.2, 20. ]])

In [66]:
A.sum(axis=1)

array([ 9, 15, 18])

In [67]:
A.sum(axis=0)

array([ 9, 14, 19])

In [70]:
A.trace() # сумма диагональных элементов

15

In [72]:
np.hstack((A, B))

array([[2. , 3. , 4. , 2. , 3. ],
       [1. , 6. , 8. , 8. , 0. ],
       [6. , 5. , 7. , 2.5, 3. ]])

In [74]:
np.vstack((A,A))

array([[2, 3, 4],
       [1, 6, 8],
       [6, 5, 7],
       [2, 3, 4],
       [1, 6, 8],
       [6, 5, 7]])